version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = "p:yellow"
    background = "p:transparent"
    Text = ''
    # template = "<p:yellow,p:transparent></><p:transparent,p:yellow>\uf07b </><,p:crust> {{ .Path }}</><p:crust,p:transparent></> "
    template = """\
          <p:yellow,p:transparent></>\
          <p:transparent,p:yellow>󰉋 </>\
          <,p:crust> {{ .Path }}</>\
          <p:crust,transparent></> """
      
    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground_templates = [
       '{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}',
       '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', 
       '{{ if gt .Ahead 0 }}p:white{{ end }}']
    template = """\
        <p:blue,p:transparent></>\
        <p:transparent,p:blue>{{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }}{{ else }}󰊢 {{ end }}</> \
        {{ .HEAD }}\
        {{ if not .UpstreamGone }}{{ if gt .Ahead 0 }} 󰅧 {{ .Ahead }}{{ end }}{{ if gt .Behind 0 }} 󰅢 {{ .Behind }}{{ end }}{{ end }}\
        {{ if .Working.Changed }} 󰇙  \
          {{if gt .Working.Added 0 }} <p:green,> {{ .Working.Added }}</>{{end}}\
          {{if gt .Working.Modified 0 }} <p:blue,> {{ .Working.Modified }}</>{{end}}\
          {{if gt .Working.Deleted 0 }} <p:red,>󰗩 {{ .Working.Deleted }}</>{{end}}\
          {{if gt .Working.Unmerged 0 }} <p:mauve,> {{ .Working.Unmerged }}</>{{end}}\
          {{if gt .Working.Untracked 0 }} <p:gray,> {{ .Working.Untracked }}</>{{end}}\
        {{ end }}\
        {{ if .Staging.Changed }} 󰇙  {{ .Staging.String }}{{ end }} \
        <p:crust,transparent></>"""
    background = 'p:crust'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "elixir"
    style = "plain"
    foreground = "p:mauve"
    background = "p:crust"
    template = """\
          <p:mauve,p:transparent> </>\
          <p:transparent,p:mauve> </> \
           {{ .Full }}\ 
          <p:crust,transparent></>"""

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = ' '
    Text = ''

[transient_prompt]
background = 'transparent'
foreground = 'yellow'
template = '  '

[secondary_prompt]
background = 'p:transparent'
foreground = 'p:yellow'
template = '❯ '

[palette]
transparent = "#1E1E2E"
yellow = "#F9E2AF"
blue = "#89B4FA"
red = "#F38BA8"
green = "#A6E3A1"
teal = "#94E2D5"
crust = "#11111B"
gray = "#6C7086"
mauve = "#CBA6F7"


