#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    Text = ''
    template = '{{ .Path }}'
      
    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = '#6C6C6C'
    # template = " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}"
    template = " <#CBA6F7>{{ .HEAD }}</>{{if gt .Ahead 0 }} <#A6E3A1>↑{{ .Ahead }}</>{{ end }}{{if gt .Behind 0 }} <#F38BA8>↓{{ .Behind }}</>{{ end }}|{{ if .Working.Changed }}<#89B4FA>\uf044</> {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}"

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    foreground = 'grey'

    [blocks.segments.properties]
      threshold = 5000
      style = 'lucky7' 

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = ' '
    Text = ''

[transient_prompt]
  background = 'transparent'
  foreground = 'yellow'
  template = '  '

[secondary_prompt]
  background = 'transparent'
  foreground = 'yellow'
  template = '❯ '
