return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = { "windwp/nvim-ts-autotag" },
	build = ":TSUpdate",
	branch = "master",
	lazy = false,
	cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
	config = function()
		local treesitter = require("nvim-treesitter.configs")

		local opts = {
			indent = { enable = true },
			highlight = { enable = true },
			folds = { enable = true },
			autotag = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"cmake",
				"css",
				"diff",
				"dockerfile",
				"eex",
				"elixir",
				"erlang",
				"gitignore",
				"go",
				"gomod",
				"heex",
				"html",
				"hyprlang",
				"javascript",
				"jsdoc",
				"json",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"meson",
				"ninja",
				"printf",
				"python",
				"query",
				"regex",
				"rust",
				"sql",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		}

		treesitter.setup(opts)
	end,
}
