bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind-key R
bind R source-file ~/.config/.tmux.conf

# Open a large popup with Ctrl+b P
unbind-key w
bind-key w display-popup -w 80% -h 80% -E

set -g mouse on
